// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RateLimiter.Persistence.Db;

#nullable disable

namespace RateLimiter.Persistence.Migrations
{
    [DbContext(typeof(RateLimiterDbContext))]
    partial class RateLimiterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RateLimiter.Persistence.Entities.RateLimitPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Capacity")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double>("RefillRatePerSecond")
                        .HasColumnType("double precision");

                    b.Property<string>("ResourcePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Priority");

                    b.ToTable("rate_limit_policies", (string)null);
                });

            modelBuilder.Entity("RateLimiter.Persistence.Entities.TokenBucketStateEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .HasColumnType("text");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastRefillUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Tokens")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("SubjectId", "Resource", "PolicyId");

                    b.ToTable("token_bucket_states", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
